dictionary = {
    "en": {
        "こんにちは、": "Hello, ",
        "さん！": "!",
        "サーバーを起動する": "Start the server",
        "サーバーは既に起動しています": "The server is already running",
        "サーバーを起動します": "Starting the server",
        "しばらくおまちください。": "Please wait a moment.",
        "ワールドのシード値を設定する。seed引数を設定せずに実行できます。": "Set the seed value of the world",
        "シード値": "Seed value",
        "シード値を変更しました": "Seed value has been changed",
        "シード値が設定されていないので、世界はランダムに生成されます。": "The seed value is not set, so the world will be generated randomly.",
        "新しいシード値: ": "The seed value is set as follows: ",
        "最大プレイヤー数を変更する": "Change the maximum number of players",
        "最大プレイヤー数": "Maximum number of players",
        "最大プレイヤー数を変更しました": "Maximum number of players has been changed",
        "新しい最大プレイヤー数: ": "The maximum number of players is set as follows: ",
        "PVPの設定を変更する": "Change the PVP setting",
        "オンかオフか": "ON or OFF",
        "オン": "ON",
        "オフ": "OFF",
        "PVPの設定を変更しました": "PVP setting has been changed",
        "新しいPVPの設定: ": "The PVP setting is set as follows: ",
        "ハードコアの設定を変更する": "Change the hardcore setting",
        "ハードコアの設定を変更しました": "Hardcore setting has been changed",
        "新しいハードコアの設定: ": "The hardcore setting is set as follows: ",
        "ゲーム難易度を変更する": "Change the game difficulty",
        "ゲーム難易度": "Game difficulty",
        "ピースフル": "Peaceful",
        "イージー": "Easy",
        "ノーマル": "Normal",
        "ハード": "Hard",
        "ゲーム難易度を変更しました": "Game difficulty has been changed",
        "新しいゲーム難易度: ": "The game difficulty level is set as follows: ",
        "遊ぶワールドを変更する。存在しないワールド名を入力することで、新しいワールドが生成される。": "Change the world to play. Entering a non-existent world name will generate a new world.",
        "ワールド名": "World name",
        "遊ぶワールドを変更しました": "The world to play has been changed",
        "次のワールドが読み込まれます: ": "The following world will be loaded: ",
        "server.propertiesを直接編集する。※間違えないように慎重に使ってください！": "Edit server.properties directly. *Use carefully to avoid mistakes!",
        "プロパティ名": "Property name",
        "次に一致する設定が見つかりませんでした:\n": "No matching settings were found:\n",
        "一致する設定が見つかりました:\n": "Matching settings were found:\n",
        "`=`に続く設定したい値を入力してください。": "Please enter the value you want to set after `=`.",
        "時間切れです。もう一度やり直してください。": "Time out. Please try again.",
        "設定を変更しました": "The setting has been changed",
        "設定を以下のように編集しました。\n": "The setting has been edited as follows:\n",
        "プロパティ名の一部を指定して一致するプロパティを検索する": "Search for properties that match the specified part of the property name",
        "プロパティ名の一部": "Part of the property name",
        "一致するプロパティが見つかりました": "Matching properties were found",
        "次のプロパティが見つかりました:\n": "The following properties were found:\n",
        "このbotをログアウトさせる": "Log out this bot",
        "ログアウトします": "Logging out",
        "botは停止されます。": "The bot will be stopped.",
        "エラー：サーバーが起動中です": "Error: The server is running",
        "そのコマンドを実行するには、サーバーを終了してください。": "To execute that command, please stop the server.",
    }
}